### PR TITLE
Allow path to NPM to be customized.

### PR DESCRIPTION
**Pull request by scottaj**

### CODE REVIEW

**Comment by azer** [comment]
:+1:

**Comment by azer** [comment]
@scottaj would you like to move this to its own organization so you can be its admin ? nowadays I'm not actively working on JS and you seem like more experienced in elisp

**Comment by scottaj** [comment]
@azer That's up to you. I am fine working on it as is, since I can merge PRs and such. I have a few things i'd like to do with the project just to make my NPM workflows easier, but I want to respect your ownership of it as well.

**Comment by scottaj** [comment]
Also, I've been doing elisp development for all of a month, so I'm not really that experienced :laughing:

**Comment by azer** [comment]
oh, ok :)

**Pull request merged**
